/*
  GEMI WEARS product catalogue
  ---------------------------
  To replace an image later, change only the `image` or `images` path below.
  Leave `image: null` for products that should show the premium COMING SOON card.
*/
window.GEMI_BRAND = {
  name: "GEMI WEARS",
  shortName: "GEMI",
  slogan: "Together. Stronger. Forever.",
  logo: "assets/brand/gemi-wears-logo.png",
  heroImage: "assets/brand/model-hero.jpeg"
};

window.GEMI_PRODUCTS = [
  // Shoes
  { id: "unity-01", name: "UNITY 01", category: "Shoes", type: "sneaker", price: 85000, badge: "Signature", isNew: true, image: "assets/products/unity-01.png", images: ["assets/products/unity-01.png", "assets/products/unity-01-side.png", "assets/products/unity-01-front.png"], description: "The founding GEMI silhouette, finished in black, gold and cream.", details: "A sculpted lifestyle sneaker with premium panels, cushioned support and the four-hands emblem.", colors: ["Black / Gold / Cream"], sizes: ["39", "40", "41", "42", "43", "44", "45"] },
  { id: "loyalty-02", name: "LOYALTY 02", category: "Shoes", type: "sneaker", price: 0, badge: "Coming soon", isNew: true, image: null, description: "Cream and green, arriving soon.", details: "New product photography will be added here when available.", colors: ["Cream / Green"], sizes: ["39", "40", "41", "42", "43", "44", "45"] },
  { id: "purpose-03", name: "PURPOSE 03", category: "Shoes", type: "sneaker", price: 0, badge: "Coming soon", image: null, description: "An all-black GEMI silhouette, arriving soon.", details: "New product photography will be added here when available.", colors: ["All Black"], sizes: ["39", "40", "41", "42", "43", "44", "45"] },
  { id: "legacy-04", name: "LEGACY 04", category: "Shoes", type: "sneaker", price: 0, badge: "Coming soon", image: null, description: "Off-white and sand, arriving soon.", details: "New product photography will be added here when available.", colors: ["Off White / Sand"], sizes: ["39", "40", "41", "42", "43", "44", "45"] },
  { id: "ascend-05", name: "ASCEND 05", category: "Shoes", type: "sneaker", price: 0, badge: "Coming soon", image: null, description: "Black and olive, arriving soon.", details: "New product photography will be added here when available.", colors: ["Black / Olive"], sizes: ["39", "40", "41", "42", "43", "44", "45"] },

  // Hoodies
  { id: "icon-hoodie", name: "ICON HOODIE", category: "Hoodies", type: "hoodie", price: 0, badge: "Coming soon", image: null, description: "A black GEMI hoodie, arriving soon.", details: "New product photography will be added here when available.", colors: ["Black"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "future-hoodie", name: "FUTURE HOODIE", category: "Hoodies", type: "hoodie", price: 55000, badge: "New release", isNew: true, image: "assets/products/future-hoodie.png", images: ["assets/products/future-hoodie.png"], description: "A cream heavyweight hoodie with the GEMI global-vision graphic.", details: "Premium cotton fleece with front and back artwork, finished with a refined GEMI label.", colors: ["Cream"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "legacy-hoodie", name: "LEGACY HOODIE", category: "Hoodies", type: "hoodie", price: 52000, badge: "Archive", image: null, mediaMessage: "Legacy<br>Hoodie", mediaCaption: "Product image update", description: "A charcoal GEMI hoodie from the Legacy collection.", details: "A new studio product image will appear here once the original source image is replaced.", colors: ["Charcoal"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "unity-hoodie", name: "UNITY HOODIE", category: "Hoodies", type: "hoodie", price: 0, badge: "Coming soon", image: null, description: "A black UNITY hoodie, arriving soon.", details: "New product photography will be added here when available.", colors: ["Black"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "loyalty-hoodie", name: "LOYALTY HOODIE", category: "Hoodies", type: "hoodie", price: 0, badge: "Coming soon", image: null, description: "A cream LOYALTY hoodie, arriving soon.", details: "New product photography will be added here when available.", colors: ["Cream"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "purpose-hoodie", name: "PURPOSE HOODIE", category: "Hoodies", type: "hoodie", price: 0, badge: "Coming soon", image: null, description: "A charcoal PURPOSE hoodie, arriving soon.", details: "New product photography will be added here when available.", colors: ["Charcoal"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "legacy-sand-hoodie", name: "LEGACY HOODIE", category: "Hoodies", type: "hoodie", price: 0, badge: "Coming soon", image: null, description: "A sand LEGACY hoodie, arriving soon.", details: "New product photography will be added here when available.", colors: ["Sand"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "ascend-hoodie", name: "ASCEND HOODIE", category: "Hoodies", type: "hoodie", price: 0, badge: "Coming soon", image: null, description: "An olive ASCEND hoodie, arriving soon.", details: "New product photography will be added here when available.", colors: ["Olive"], sizes: ["S", "M", "L", "XL", "XXL"] },

  // T-shirts
  { id: "global-vision-tee", name: "GLOBAL VISION TEE", category: "T-Shirts", type: "tee", price: 30000, badge: "New release", isNew: true, image: "assets/products/global-vision-tee.png", images: ["assets/products/global-vision-tee.png"], description: "A cream GEMI tee carrying the Global Vision artwork.", details: "A relaxed streetwear tee with front and back global-vision graphics.", colors: ["Cream"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "comfort-01-tee", name: "COMFORT 01 TEE", category: "T-Shirts", type: "tee", price: 28000, badge: "Core collection", image: "assets/products/comfort-01-tee.png", images: ["assets/products/comfort-01-tee.png"], description: "A charcoal statement tee built for everyday comfort.", details: "A relaxed-fit shirt with GEMI front and back artwork, supplied exactly as uploaded.", colors: ["Charcoal"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "unity-tee", name: "UNITY TEE", category: "T-Shirts", type: "tee", price: 0, badge: "Coming soon", image: null, description: "A black UNITY tee, arriving soon.", details: "New product photography will be added here when available.", colors: ["Black"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "legacy-tee", name: "LEGACY TEE", category: "T-Shirts", type: "tee", price: 0, badge: "Coming soon", image: null, description: "A charcoal LEGACY tee, arriving soon.", details: "New product photography will be added here when available.", colors: ["Charcoal"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "loyalty-tee", name: "LOYALTY TEE", category: "T-Shirts", type: "tee", price: 0, badge: "Coming soon", image: null, description: "A cream LOYALTY tee, arriving soon.", details: "New product photography will be added here when available.", colors: ["Cream"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "purpose-tee", name: "PURPOSE TEE", category: "T-Shirts", type: "tee", price: 0, badge: "Coming soon", image: null, description: "A charcoal PURPOSE tee, arriving soon.", details: "New product photography will be added here when available.", colors: ["Charcoal"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "ascend-tee", name: "ASCEND TEE", category: "T-Shirts", type: "tee", price: 0, badge: "Coming soon", image: null, description: "An olive ASCEND tee, arriving soon.", details: "New product photography will be added here when available.", colors: ["Olive"], sizes: ["S", "M", "L", "XL", "XXL"] },

  // Joggers, shorts and denim
  { id: "girls-charcoal-jogger", name: "GIRLS CHARCOAL JOGGER", category: "Joggers", type: "jogger", price: 42000, badge: "New release", isNew: true, image: "assets/products/girls-charcoal-joggers.png", images: ["assets/products/girls-charcoal-joggers.png"], description: "Charcoal cargo joggers with the GEMI signature emblem.", details: "A relaxed cargo fit with utility pockets, ribbed cuffs and subtle gold details.", colors: ["Charcoal"], sizes: ["XS", "S", "M", "L", "XL"] },
  { id: "unity-jogger", name: "UNITY JOGGER", category: "Joggers", type: "jogger", price: 0, badge: "Coming soon", image: null, description: "A black and charcoal UNITY jogger, arriving soon.", details: "New product photography will be added here when available.", colors: ["Black / Charcoal"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "legacy-jogger", name: "LEGACY JOGGER", category: "Joggers", type: "jogger", price: 0, badge: "Coming soon", image: null, description: "A charcoal LEGACY jogger, arriving soon.", details: "New product photography will be added here when available.", colors: ["Charcoal"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "ascend-jogger", name: "ASCEND JOGGER", category: "Joggers", type: "jogger", price: 0, badge: "Coming soon", image: null, description: "An olive ASCEND jogger, arriving soon.", details: "New product photography will be added here when available.", colors: ["Olive"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "unity-cargo-shorts", name: "UNITY CARGO SHORTS", category: "Shorts", type: "shorts", price: 32000, badge: "New release", isNew: true, image: "assets/products/unity-cargo-shorts.png", images: ["assets/products/unity-cargo-shorts.png"], description: "Charcoal cargo shorts with sharp utility pockets and gold details.", details: "A functional streetwear short with adjustable waist and prominent cargo storage.", colors: ["Charcoal"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "legacy-sweat-shorts", name: "LEGACY SWEAT SHORTS", category: "Shorts", type: "shorts", price: 28000, badge: "Core collection", image: "assets/products/legacy-sweat-shorts.png", images: ["assets/products/legacy-sweat-shorts.png"], description: "Charcoal sweat shorts with a clean, signature finish.", details: "Comfort-led shorts with an elastic waist, deep pockets and a small four-hands emblem.", colors: ["Charcoal"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "purpose-denim-shorts", name: "PURPOSE DENIM SHORTS", category: "Shorts", type: "shorts", price: 0, badge: "Coming soon", image: null, description: "Black shine denim shorts, arriving soon.", details: "New product photography will be added here when available.", colors: ["Black Shine"], sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: "unity-shine-denim", name: "UNITY SHINE DENIM", category: "Denim", type: "denim", price: 65000, badge: "New release", isNew: true, image: "assets/products/unity-shine-denim.png", images: ["assets/products/unity-shine-denim.png"], description: "Black wide-leg denim with signature dot-shine detail.", details: "A statement denim silhouette with a gem-like surface treatment and four-hands back-pocket emblem.", colors: ["Black / Signature Dot Shine"], sizes: ["28", "30", "32", "34", "36", "38"] },
  { id: "legacy-denim", name: "LEGACY DENIM", category: "Denim", type: "denim", price: 0, badge: "Coming soon", image: null, description: "Charcoal wash LEGACY denim, arriving soon.", details: "New product photography will be added here when available.", colors: ["Charcoal Wash"], sizes: ["28", "30", "32", "34", "36", "38"] },
  { id: "ascend-baggy-denim", name: "ASCEND BAGGY DENIM", category: "Denim", type: "denim", price: 55000, badge: "New release", isNew: true, image: "assets/products/ascend-baggy-denim.png", images: ["assets/products/ascend-baggy-denim.png"], description: "Light vintage-blue baggy denim finished with GEMI detail.", details: "A relaxed wide-leg jean with a vintage wash and signed back pocket.", colors: ["Light Vintage Blue"], sizes: ["28", "30", "32", "34", "36", "38"] }
];

window.GEMI_CURRENCY = new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 });
